# include: package:flutter_lints/flutter.yaml
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
  exclude:
    - "build/**"
    - "**/gen/**"
    - "**.g.dart"
    - "**.freezed.dart"
  plugins:
    - custom_lint

linter:
  rules:
    omit_local_variable_types: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    prefer_single_quotes: false
