name: gcpro
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  animations: ^2.0.11
  auto_route: ^10.0.1
 
  cached_network_image: ^3.4.1
  chips_choice: ^3.0.1
  connectivity_plus: ^6.1.2
  country_code_picker: ^3.1.0
  country_picker: ^2.0.27
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.2.1
  # device_preview: ^1.2.0
  dio: ^5.7.0
  dio_http_formatter: ^3.3.0
  equatable: ^2.0.7
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1 
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  form_validator: ^2.1.1
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hive_flutter: ^1.1.0
  image: ^4.5.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  pin_code_fields: ^8.0.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0
  socket_io_client: ^3.0.2
  state_notifier: ^1.0.0
  timeago: ^3.7.0
  uuid: ^4.5.1
  zxing2: ^0.2.3

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.14
  custom_lint:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  test_coverage_badge: ^0.3.2
  very_good_analysis: ^7.0.0

flutter_gen:
  output: lib/gen/

  colors:
    enabled: false

  integrations:
    flutter_localizations: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    # - assets/google_fonts/

scripts:
  build: dart pub run build_runner build --delete-conflicting-outputs
  watch: dart pub run build_runner watch --delete-conflicting-outputs
  splash: dart run flutter_native_splash:create
